### ISSUE TITLE
vl_kmeans for test phase

### ISSUE THREAD

**Issue by sophiatse** [rezazad68/Dynamic-3D-Action-Recognition-on-RGB-D-Videos#3]
I have a question about the Vlad part in your code, why do you use training features' cluster parameters to get test features' vlad ? why vl_kmeans only used to get training features' clusters?
could you please help me?
thanks advanced!

**Comment by rezazad68** [comment]
Hello,

Thanks for your interest and sorry for the late reply. We use train set to learn the visual words. Each visual word is just a center of a cluster, thus, we learn them through the training process (cluster algorithm with k means) using the train set. Once we learned the visual words now in test time we seek which visual words exist in the test sample, so we need training information. Best
